name: "ST-CAFFEINE"

on: [ push ]
  # schedule:
    # - cron: '0 6 * * *'  # testing trigger time

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checking out repository content"
        uses: actions/checkout@v3

      - name: "Pushing an empty commit"
        run: |
          echo "Initializing..."
          git config --global user.name "${{secrets.USER_NAME}}"
          git config --global user.email "${{secrets.USER_EMAIL}}"
          git push -u origin master