name: "ST-CAFFEINE"

on: [ push ]
  # schedule:
    # - cron: '0 6 * * *'  # testing trigger time

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checking out repository content"
        uses: actions/checkout@v3
        with: 
          repository: gowthamr56/portfolio-website
          persist-credentials: false

      # - name: "Empty commit"
      #   run: |
      #     echo "Initializing empty commit"
      #     git config --global user.name "${{secrets.USER_NAME}}"
      #     git config --global user.email "${{secrets.USER_EMAIL}}"
      #     git config --global user.passwd "${{secrets.PASSWD}}"
      #     git commit --allow-empty -m "empty commit"

      # - name: "Pushing a commit"
      #   uses: ad-m/github-push-action@master
      #   with: 
      #     github_token: ${{secrets.TOKEN}}

      - run: |
          echo "Initializing..."
          git remote add target-origin https://github.com/gowthamr56/portfolio-website.git
          git remote --verbose