name: "ST-CAFFEINE"

on: [ push ]
  # schedule:
    # - cron: '0 6 * * *'  # testing trigger time

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checking out repository content"
        uses: actions/checkout@v3
        with: 
          repository: gowthamr56/portfolio-website
          persist-credentials: false

      - name: "Empty commit"
        run: |
          echo "--AUTHENTICATION--"
          git config --global user.name "${{secrets.USER_NAME}}"
          git config --global user.email "${{secrets.USER_EMAIL}}"
          git config --global user.passwd "${{secrets.PASSWD}}"

          echo "--EMPTY COMMIT--"
          git commit --allow-empty -m "empty commit"

          echo "--ADD TARGET ORIGIN--"
          git remote add target-origin https://github.com/gowthamr56/portfolio-website.git

          echo "--PUSH--"
          git push -u target-origin master

      # - name: "Pushing a commit"
      #   uses: ad-m/github-push-action@master
      #   with: 
      #     github_token: ${{secrets.TOKEN}}
